spring.application.name=TuConjuntoSpring

server.port=8081

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tuconjuntoapp?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false
spring.messages.encoding=UTF-8
